# Generated by Django 6.0.6 on 2026-06-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'db_table': 'kategori',
                'ordering': ['nama_kategori'],
            },
        ),
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_virus', models.CharField(max_length=200)),
                ('nama_ilmiah', models.CharField(max_length=200, unique=True)),
                ('deskripsi', models.TextField()),
                ('cara_berkembang_biak', models.TextField()),
                ('bentuk', models.CharField(choices=[('helical', 'Helical'), ('icosahedral', 'Icosahedral'), ('prolate', 'Prolate'), ('envelope', 'Envelope'), ('complex', 'Complex')], max_length=50)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='virus/gambar/')),
                ('referensi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virus_list', to='virus.kategori')),
            ],
            options={
                'verbose_name': 'Virus',
                'verbose_name_plural': 'Virus',
                'db_table': 'virus',
                'ordering': ['nama_virus'],
            },
        ),
    ]
